import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import ThemeClient from "../theme-client"; 

const poppins = Poppins({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${poppins.variable} antialiased`}>
        <ThemeClient>
          {children}
        </ThemeClient>
      </body>
    </html>
  );
}
